openapi: 3.0.3
info:
  title: Insurance Orders
  description: |-
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: Orders
    description: Insurance orders
paths:
  /orders:
    post:
      tags:
        - Orders
      summary: Creates a new insurance order
      operationId: createInsuranceOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreateResponse'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        '500':
          description: Application general error
    get:
      tags:
        - Orders
      summary: Finds orders (optionally by customer id)
      operationId: getOrders
      parameters:
        - in: query
          name: customerId
          schema:
            type: string
            format: uuid
          required: false
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseList'
        '404':
          description: Not Found
        '500':
          description: Application general error

  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Returns an order by its id
      operationId: getOrder
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Not Found
        '500':
          description: Application general error
    delete:
      tags:
        - Orders
      summary: Cancel an order by its id
      operationId: cancelOrder
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity
        '500':
          description: Application general error
components:
  schemas:
    Coverage:
      type: object
      properties:
        name:
          type: string
          example: 'Roubo'
        amount:
          type: number
          format: double
          example: 20000.99
    StatusHistoryItem:
      type: object
      properties:
        status:
          type: string
          example: 'RECEIVED'
        timestamp:
          type: string
          format: date-time
    OrderCreateRequest:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        productId:
          type: integer
          example: 986554
        category:
          type: string
          example: 'AUTO'
        totalMonthlyPremiumAmount:
          type: number
          format: double
          example: 2587.95
        insuredAmount:
          type: number
          format: double
          example: 250000.52
        paymentMethod:
          type: string
          example: 'CREDIT_CARD'
        salesChannel:
          type: string
          example: 'MOBILE'
        coverages:
          type: array
          items:
            $ref: "#/components/schemas/Coverage"
        assistances:
          type: array
          items:
            type: string
          example: ['Guincho até 250km', 'Troca de Óleo', 'Chaveiro 24h']
    OrderCreateResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        finishedAt:
          type: string
          format: date-time
        status:
          type: string
          example: 'APPROVED'
        customerId:
          type: string
          format: uuid
        classification:
          type: string
          example: 'REGULAR'
        productId:
          type: integer
          example: 986554
        category:
          type: string
          example: 'AUTO'
        totalMonthlyPremiumAmount:
          type: number
          format: double
          example: 2587.95
        insuredAmount:
          type: number
          format: double
          example: 250000.52
        paymentMethod:
          type: string
          example: 'CREDIT_CARD'
        salesChannel:
          type: string
          example: 'MOBILE'
        coverages:
          type: array
          items:
            $ref: "#/components/schemas/Coverage"
        assistances:
          type: array
          items:
            type: string
          example: ['Guincho até 250km', 'Troca de Óleo', 'Chaveiro 24h']
        history:
          type: array
          items:
            $ref: "#/components/schemas/StatusHistoryItem"
    OrderResponseList:
      type: array
      items:
        $ref: "#/components/schemas/OrderResponse"
